controller_manager:
  ros__parameters:
    update_rate: 60

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'

ackermann_controller:
  ros__parameters:
    front_steering: true
    open_loop: false
    position_feedback: false
    rear_wheels_names: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
    front_wheels_names: ['front_left_wheel_steering_joint', 'front_right_wheel_steering_joint']
    use_stamped_vel: true
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odem_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]

    wheelbase: 1.7
    front_wheel_track: 1.0
    rear_wheel_track: 0.8
    front_wheels_radius: 0.30
    rear_wheels_radius: 0.30
