---
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: BIDIRECTIONAL

- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/tf"
  gz_topic_name: "/model/vehicle_blue/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS"
  #- ros_topic_name: "/vehicle_blue/odometry_with_covariance"
  #  gz_topic_name: "/model/vehicle_blue/odometry_with_covariance"
  #  ros_type_name: "nav_msgs/msg/Odometry"
  #  gz_type_name: "ignition.msgs.OdometryWithCovariance"
  #  direction: GZ_TO_ROS

  #- ros_topic_name: "/scan"
  #  gz_topic_name: "/scan"
  #  ros_type_name: "sensor_msgs/msg/LaserScan"
  #  gz_type_name: "ignition.msgs.LaserScan"
  #  direction: GZ_TO_ROS

  #- ros_topic_name: "/camera/front_raw"
  #  gz_topic_name: "/camera_front"
  #  ros_type_name: "sensor_msgs/msg/Image"
  #  gz_type_name: "ignition.msgs.Image"
  #  direction: GZ_TO_ROS
  #
  #- ros_topic_name: "/imu"
  #  gz_topic_name: "/imu"
  #  ros_type_name: "sensor_msgs/msg/Imu"
  #  gz_type_name: "ignition.msgs.IMU"
  #  direction: GZ_TO_ROS
  #
  #- ros_topic_name: "/camera/left_raw"
  #  gz_topic_name: "/camera_left"
  #  ros_type_name: "sensor_msgs/msg/Image"
  #  gz_type_name: "ignition.msgs.Image"
  #  direction: GZ_TO_ROS
  #- ros_topic_name: "/camera/right_raw"
  #  gz_topic_name: "/camera_right"
  #  ros_type_name: "sensor_msgs/msg/Image"
  #  gz_type_name: "ignition.msgs.Image"
  #  direction: GZ_TO_ROS
  #- ros_topic_name: "/camera/rear_raw"
  #  gz_topic_name: "/camera_rear"
  #  ros_type_name: "sensor_msgs/msg/Image"
  #  gz_type_name: "ignition.msgs.Image"
  #  direction: GZ_TO_ROS
